# Generated by Django 4.2.3 on 2024-03-23 16:44

import DentistBook.client.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), DentistBook.client.validators.validate_client_name])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), DentistBook.client.validators.validate_client_name])),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), DentistBook.client.validators.validate_client_city_name])),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8), DentistBook.client.validators.validate_client_phone_number])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='client-profile-pictures', validators=[DentistBook.client.validators.validate_client_picture_file_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
